// <auto-generated />
using ExampleApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExampleApp.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191203143207_V2StatesCountries")]
    partial class V2StatesCountries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ExampleApp.Country", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Locale");

                    b.HasKey("Id", "Locale");

                    b.ToTable("address_country");
                });

            modelBuilder.Entity("ExampleApp.State", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Locale");

                    b.Property<int>("CountryId");

                    b.HasKey("Id", "Locale");

                    b.ToTable("address_state");
                });
#pragma warning restore 612, 618
        }
    }
}
